### ISSUE TITLE
problem with context menus

### ISSUE THREAD

**Issue by Ronildo93** [VaughnValle/blue-sky#1]
I'm having trouble with blur in context menus:

https://imgur.com/TOLjBjm

how can I solve?

**Comment by VaughnValle** [comment]
I can't test blur for context menus at the moment as BSPWM doesn't use context menus. It has something to do with your compositor for sure. What picom version/fork are you using?

**Comment by Ronildo93** [comment]
I'm using this version:
![example](https://imgur.com/YNlEr6Q)

**Comment by VaughnValle** [comment]
Great! Glad you were able to solve it. Closing this issue now
