### ISSUE TITLE
Chrome Startpage and Theme

### ISSUE THREAD

**Issue by phneutral26** [VaughnValle/blue-sky#12]
You dont mention your Chrome Startpage.... Maybe make a github.io page for it? or give me the source code and i do a hosted Webpage.

**Comment by phneutral26** [comment]
Do you have any updates for me? Do you even use this rice any longer?

**Comment by VaughnValle** [comment]
Unfortunately, I no longer use this rice, and the configs for the chrome startpage were lost. However, what I did was look up various browser startup pages and theming it with the blue background to achieve the desired look. Hope it helps!
