### ISSUE TITLE
Laptop issues

### ISSUE THREAD

**Issue by TQMatvey** [VaughnValle/blue-sky#13]
polybar: No Wifi or battery at all.
went to polybar config changed wifi from net0 to wlan0, still only sound icon appears, everything else works great... 
no battery, no icon so i cant see my battery %. rebooted checked config, no luck

**Comment by Devansh-Patel** [comment]
Also, you can do the same think for battery percentage enter the ~/.config/polybar/current.ini file and enter your battery and adapter name. You can check it by doing ls in /sys/class/power_supply directory. Just see the name of your battery and adapter from this directory and enter it into the current.ini file.

**Comment by TQMatvey** [comment]
> For WiFi, you need to change your interface in current.ini file in ~/.config/polybar/ but it wouldn't make sure that the left click functionality would work. I am using PopOS and I don't know what command should I write in "click-left" for gnome.

i am also on pop os using this rice, i got everything to work, would be great if i could for example move my cursor to battery and see the % haha, Thanks!!!
