### ISSUE TITLE
Cmake error for Polybar - missing package libuv

### ISSUE THREAD

**Issue by Puzzlers100** [VaughnValle/blue-sky#14]
I was installing this and came across some errors. It's possible I missed a step, however, I couldn't make polybar since libuv1-dev was not installed on my build of pop_Os. Not sure if it's an issue but it should probably be included in the dependencies for polybar

**Comment by VaughnValle** [comment]
Fixed in https://github.com/VaughnValle/blue-sky/commit/456e42998756605f2f8ea0ec3a319a022ec09519

Apologies for the late response. Took a break from this a long time ago
