### ISSUE TITLE
Error in debian 11 with the package "libuv".

### ISSUE THREAD

**Issue by cesar-julio** [VaughnValle/blue-sky#17]
I am following the installation manual, but when I run the command "cmake .." I get an error with the "libuv" dependency, it tells me that it does not exist, I tried to install that package but it tells me that it does not exist to install it. Any suggestions.

**Comment by suhaskv1** [comment]
Check out the wiki for the fix. https://github.com/polybar/polybar/wiki/Compiling

Depending on your distro, the required "libuv" version is to be installed.

**Comment by atraxsrc** [comment]
sudo apt install libuv1.dev

**Comment by eboatwright** [comment]
Yes, this worked :+1:

**Comment by VaughnValle** [comment]
Terribly sorry for only seeing this now. 

Thanks for this. Added it to the README
