### ISSUE TITLE
cant apply slimlock

### ISSUE THREAD

**Issue by Firefox289** [VaughnValle/blue-sky#5]
sudo cp default ~/Downloads/blue-sky/slim/themes
cp: cannot stat 'default': No such file or directory

sudo cp slim.conf /etc && sudo cp slimlock.conf /etc sudo cp default /usr/share/slim/themes
cp: cannot stat 'slim.conf': No such file or directory

**Comment by phneutral26** [comment]
first cd into Downloads/blue-sky/slim
then do the cp command.

**Comment by Firefox289** [comment]
sudo cp default ~/Downloads/blue-sky/slim/themes
cp: -r not specified; omitting directory 'default'



sudo cp slim.conf /etc && sudo cp slimlock.conf /etc sudo cp default /usr/share/slim/themes
[sudo] password for firefox289:
cp: -r not specified; omitting directory '/etc'
cp: cannot stat 'sudo': No such file or directory
cp: cannot stat 'cp': No such file or directory
cp: -r not specified; omitting directory 'default'

**Comment by phneutral26** [comment]
cd ~/Downloads/blue-sky/slim
Cp -r default /usr/share/slim/themes
Then you should have the first command for the default folder. I know that's annoying to hear, but you have to understand it. The second command is difficult, so seperate the command into two cp commands and know what is doing what ;)

**Comment by Firefox289** [comment]
bada Boom pao ERROR:blue-sky/slim on  master
❯ Cp -r default /usr/share/slim/themes
zsh: command not found: Cp

blue-sky/slim on  master
❯ cp -r default /usr/share/slim/themes
cp: cannot create regular file '/usr/share/slim/themes/default/background.png': Permission denied
cp: cannot create regular file '/usr/share/slim/themes/default/panel.png': Permission denied
cp: cannot create regular file '/usr/share/slim/themes/default/slim.theme': Permission denied

**Comment by Firefox289** [comment]
sorry im new to linux

**Comment by phneutral26** [comment]
I cant really help you... i switched to gentoo now
